version: "3.8"

services:

  minio:
    container_name: minio_test
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin123
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - 9000:9000
      - 9001:9001